### ISSUE TITLE
New 3.0 module break support for Mini? 

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-birddog-converters#13]
Does the latest 3.0 build break support for Mini until it gets new firmware? (IF?). Trying out 3.0 and get an error that says firmware required.
Thanks!

**Comment by bryce-seifert** [comment]
For now the priority in beta was supporting the latest BirdDog API 2.0 devices.

If we're getting close to release and still not Mini/Studio FW I'll work on getting some sort of compatibility into the module. Also trying to get any indication from BirdDog of when this might be, as the 1.0 API really is not in a suitable state for much of anything.

**Comment by obcocav** [comment]
Hey @bryce-seifert .  Any chance of "shoehorning" some support for the Mini's in 3.0 since still no NDI5 and the RC is coming? Thanks for your help!

**Comment by bryce-seifert** [comment]
@obcocav Returned basic support for Mini is in the latest beta. Let me know if you encounter any issues

**Comment by obcocav** [comment]
﻿Thank you!On Apr 25, 2023, at 19:11, bryce ***@***.***> wrote:﻿
@obcocav Returned basic support for Mini is in the latest beta. Let me know if you encounter any issues
