### ISSUE TITLE
Module status doesn't recover from any failure

### ISSUE THREAD

**Issue by elliotmatson** [bitfocus/companion-module-birddog-converters#27]
Occasionally, if the network gets disrupted, this module will enter a "Connection Failure" state. After the network is running again, this module doesn't seem to ever set the status back to "ok", even though http and ws connections are completing correctly.

Could I submit a PR to either:

- Add an interval that calls checkConnection()
- Add updateStatus('ok') to the websocket "open" event handler

Thanks!

**Comment by bryce-seifert** [comment]
Yeah, feel free!
